[package]
authors = ["Benno Fünfstück <benno.fuenfstueck@gmail.com>"]
name = "nix-index"
version = "0.1.0"

[dependencies]
ansi_term = "0.9.0"
async-http-client = "0.2.0"
bincode = "1.0.0-alpha2"
byteorder = "1.0.0"
clap = "2.20.5"
curl = "0.4.6"
error-chain = "0.10.0"
futures = "0.1.10"
grep = "0.1.5"
isatty = "0.1.3"
memchr = "1.0.1"
ordermap = "0.2.8"
regex = "0.2.1"
rustc-serialize = "0.3.22"
separator = "0.3.1"
serde = "0.9.7"
serde_derive = "0.9.7"
serde_json = "0.9.8"
tokio-core = "0.1.4"
tokio-curl = "0.1.9"
tokio-retry = "0.0.4"
tokio-timer = "0.1.0"
void = "1.0.2"
xdg = "2.0.0"
xml-rs = "0.3.5"
xz2 = "0.1.1"
zstd = "0.4.3"

[profile]

[profile.release]
debug = true

[[bin]]
name = "nix-index"
doc = false

[[bin]]
name = "nix-locate"
